spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/departmentdb
    username: root
    password: Santhosh@18
server:
  port: 8083
